version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - project_network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      - project_network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      - project_network
    restart: always

volumes:
  db-data:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      device: /home/nsoares-/data/db
      o: bind
  wordpress-data:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      device: /home/nsoares-/data/wp
      o: bind

networks:
  project_network:
    name: inception_network
    driver: bridge
