# version: 'version'

services:
  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  #   image: mariadb:42
  #   env_file:
  #     - .env
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mariadb_volume:/var/lib/mysql
  #   networks:
  #     - my_network
  #   restart: always


  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - 443:443
    networks:
    - my_network
    restart: always
  # volumes:
  
  # wordpress:
  #   build:
  #     context: .
  #     # dockerfile: requirements/wordpress/Dockerfile
  #     image: wordpress
  #     volumes:
  #       - ./data/wordpress:/var/www/html
  #   environment:
  #     .env
  #   networks:

networks:
  my_network:
    driver: bridge

volumes:
  mariadb_volume:


