# version: 'version'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb_volume:/var/lib/mysqlz
    networks:
      - my_network
    restart: always

    # wordpress:
    #   build:
    #     context: .
    #     # dockerfile: requirements/wordpress/Dockerfile
    #     image: wordpress
    #     volumes:
    #       - ./data/wordpress:/var/www/html
    #   environment:
    #     .env
    #   networks:

  # nginx:
  #   # build:
  #   #   context: .
  #   # dockerfile: requirements/nginx/Dockerfile
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - 80:80
  #   networks:
  #   - my_network
    # volumes:
    #       - ./data/nginx:/var/log/nginx
    #       - ./data/wordpress:/var/www/html
    #       - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    #       - ./requirements/nginx/conf.d:/etc/nginx/conf.d
    #   ports:
    #     - 80:80
    #   networks:

networks:
  my_network:
    driver: bridge

volumes:
  mariadb_volume:


